config/routes.rb
Rails.application.routes.draw do
  
root "sessions#home"
  
get '/signup' => 'users#new'
post '/signup' => 'users#create'

#my login route
get '/login' => 'sessions#new'               # displays login page 
post '/login' => 'sessions#create'           # processes login information

 #omniauth route we need when google sends back the request
get "/auth/:google_oauth2/callback" => 'sessions#google'
 
#my logout route
delete '/logout' => 'sessions#destroy'       
  
  resources :users
  #nested
  resources :comicbooks do
    resources :reviews, shallow: true
  end

end 

#NOTES TO MYSELF 

# https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-resources
#Generates shallow routes for nested resource(s). 
#When placed on a parent resource, generates shallow routes for all nested resources
#It is same as 
#resources :comicbooks do
     #resources :reviews, only: [:new, :create, :index]
#end 
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comicbook.rb
class Comicbook < ApplicationRecord
    belongs_to :user 
    has_many :reviews
    has_many :users, through: :reviews 

    validates_presence_of :title, :number  
    scope :sort_by_title, -> { order(:title) }
   
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :comicbook

  validates :rating, presence: true
  validates :comment, presence: true
  validates_length_of :comment, :maximum => 300
 

end

app/models/user.rb
class User < ApplicationRecord
    has_many :comicbooks
    has_many :reviews
    has_many :reviewed_comicbooks, -> {distinct}, through: :reviews, source: :comicbook  
    
    has_secure_password 
    validates :username, presence: true, uniqueness: true 
    validates :email, presence: true, uniqueness: true 

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in   #gives these methods access in the views! 
    before_action :redirect_if_not_logged_in

    private
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
        #if current_user is already defined equal to current_user if not find the user in the user table
        #recommended not to use @user so make sure you are consistent
        #@current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def logged_in
    !!current_user
    #or I can use !!session[:user_id]
    end

    def redirect_if_not_logged_in
        flash[:message] = "Please Login!"
        redirect_to '/' if !logged_in

        #unless logged_in
        #redirect_to root_path, notice: "Please login" #check if the notice working
        #or to keep it simple I can  redirect_to '/' if !logged_in
        #redirect_to '/' if !logged_in
      #end
    end

end

app/controllers/comicbooks_controller.rb
class ComicbooksController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_comicbook, only: [:edit, :destroy]
    before_action :set_comicbook_id, only: [:show, :update]
    

  def new
      @comicbook = Comicbook.new
  end

  def create
      #binding.pry
      @comicbook = current_user.comicbooks.build(comicbook_params)
      if @comicbook.save
         redirect_to @comicbook
      else
         render :new
      end
      
  end

  def show
      redirect_to comicbooks_path if !@comicbook
  end
 
  def index 
      @comicbooks= Comicbook.all 
  end 

  def edit 
      #binding.pry
  end 

  def update 
      
    if current_user == @comicbook.user 

        if @comicbook.update(comicbook_params)

            redirect_to comicbook_path(@comicbook)
        else
            render :edit
        end
    else
        redirect_to comicbooks_path
    end
  end 

  def destroy
      if current_user == @comicbook.user 
         @comicbook.destroy
         redirect_to comicbooks_path
      else 
         redirect_to comicbooks_path
      end 
  end 

  private

  def set_comicbook
    @comicbook = Comicbook.find(params[:id])
  end 
  def set_comicbook_id
    @comicbook = Comicbook.find_by_id(params[:id])
  end 
  
  def comicbook_params
      params.require(:comicbook).permit(:title, :number, :writer, :artist, :publisher)
  end



end

app/controllers/reviews_controller.rb
 
class ReviewsController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :set_comicbook, only: [:new, :index, :show, :edit, :create]
  before_action :set_review, only: [:show, :edit, :destroy]

  def new
    @review = @comicbook.reviews.build
  end

  def create
    #@comicbook = Comicbook.find(params[:comicbook_id])
    @review = current_user.reviews.build(review_params)
    @review.comicbook = @comicbook
      if @review.save
         redirect_to @review
         #redirect_to comicbook_reviews_path(@review.comicbook)
      else
         render :new
      end
  end

  def index 
    @reviews = @comicbook.reviews
  end
  
  
  def show
  end

  def edit
  end

  def update
    @review = Review.find(params[:id])
     if current_user == @review.user
       
        if @review.update(review_params)
           redirect_to @review
        else
           render :edit
        end 
        else 
           redirect_to comicbooks_path
      end 
  end

  def destroy
    if current_user == @review.user
       @review.destroy
       redirect_to comicbook_path(@review.comicbook)
    else 
       redirect_to comicbooks_path
    end
end 

  private
  def set_comicbook
    @comicbook = Comicbook.find_by_id(params[:comicbook_id])
  end

  def set_review
    @review = Review.find_by_id(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end 
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action  :redirect_if_not_logged_in

    def create
       #binding.pry
       @user = User.find_by(username: params[:user][:username])
       if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
        else
          flash[:message] = "Incorrect login info, please try again"
          render :new
        end
      end

      def google
        #find_or_create a user using the attributes auth
        @user = User.find_or_create_by(email: auth["info"]["email"]) do |user|
          user.username = auth["info"]["first_name"]
          user.password = SecureRandom.hex(10) #is an interface to secure random number generators which are suitable for generating session keys
        end 
        if @user.save
           session[:user_id] = @user.id
           redirect_to user_path(@user)
        else
           redirect_to '/'
        end
      end

      def destroy
        session.clear
        redirect_to root_path
      end

      private
      def auth
        request.env['omniauth.auth']
      end
    end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :redirect_if_not_logged_in, only: [:new, :create]
    def new
        @user = User.new
    end

    def create
        #binding.pry
        @user = User.new(user_params)
        if @user.save
           session[:user_id] = @user.id
        #we are logging in
           redirect_to @user 
        else
          render :new
        end
      end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id]) #this will bring nil
        redirect_to '/' if !@user   # we are directing to home if it is not a user
     end

    
private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comicbooks_helper.rb
module ComicbooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comicbooks/_form.html.erb
<%= form_for(@comicbook, local: true) do |form| %>
<%= render partial: "layouts/errors", locals: {object: @comicbook} %>

<br>
<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>
<br>
<div class="field">
  <%= form.label :number %>
  <%= form.number_field :number%>
</div>
<br>
<div class="field">
  <%= form.label :publisher %>
  <%= form.text_field :publisher %>
</div>
<br>
<div class="field">
  <%= form.label :writer %>
  <%= form.text_field :writer %>
</div>
<br>
<div class="field">
  <%= form.label :artist %>
  <%= form.text_field :artist %>
</div>
<br>
<div class="actions">
  <%= form.submit %>
</div>

<% end %>

app/views/comicbooks/edit.html.erb
<h1>Edit Comicbook</h1>
<%= render 'form', comicbook: @comicbook %>

app/views/comicbooks/index.html.erb
<h1> All Comicbooks </h1>

<% current_user.comicbooks.sort_by_title.each do |comicbook| %>
<p><%= link_to comicbook.title, comicbook_path(comicbook)%> , issue <%= comicbook.number %></p>
<% end %>

app/views/comicbooks/new.html.erb
<h1>New Comicbook</h1>
<%= render 'form' %>

app/views/comicbooks/show.html.erb
<h1> -Comicbook- </h1>

<h2> Title: <%=@comicbook.title%></h2>
<h2> Issue: <%=@comicbook.number%></h2>
<h2> Publisher: <%=@comicbook.publisher%></h2>
<h2> Writer: <%=@comicbook.writer%></h2>
<h2> Artist: <%=@comicbook.artist%></h2>
<h2>This book belongs to <%= @comicbook.user.username %> </h1>


<% if @comicbook.user == current_user %>
<%= link_to 'My Notes/Reviews', comicbook_reviews_path(@comicbook) %>
<br>
<%= link_to 'Add a New Note/Review', new_comicbook_review_path(@comicbook) %>
<br>
<br>
<button type="button"><%= link_to 'Edit', edit_comicbook_path(@comicbook) %> </button>
<button type="button"><%= link_to 'Delete', @comicbook, method: :delete, data: { confirm: 'Are you sure?' } %></button>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComicbookReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>

 <% if logged_in%>
      <%= link_to "Home", user_path(current_user)%> |
      <%= link_to "Add a Comicbook", new_comicbook_path %> |
      <%= link_to "All Comicbooks", comicbooks_path %> |
      <%= link_to "Logout", logout_path, method:"delete"%>

  <% else %>
      <%=link_to "Sign Up", signup_path %> |
      <%=link_to "Log In", login_path %>
  <% end %>


    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<h1>Edit Review for <%= @review.comicbook.title%>
<%= form_for [@comicbook, @review] do |f| %>


<% if @review.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@review.errors.count, "error") %> prohibited this from being saved:</h2>

  <ul>
    <% @review.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<br>
<div class="field">
  <%= f.label :rating %>
  <%= f.select(:rating, [1,2,3,4,5], :prompt => 'Rate') %>
</div>
<br>
<div class="field">
  <%= f.label :comment %>
  <br>
  <br>
  <%= f.text_area :comment, size: "30x5"  %>
</div>
<br>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>
<h2><%= @comicbook.title%>, issue: <%= @comicbook.number%><h2>

<h3><% @reviews.each do |r| %></h3>
<p>Reviewed by <%= r.user.username %>,  Rating: <%= r.rating %> </p>
<p><%= r.comment%></p>
<p>--------------------------------------</p>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review for <%= @comicbook.title%>, issue <%= @comicbook.number%></h1>

<%= form_for [@comicbook, @review] do |f| %>
<% if @review.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@review.errors.count, "error") %> prohibited this @review from being saved:</h2>

  <ul>
    <% @review.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<br>
<div class="field">
  <%= f.label :rating %>
  <%= f.select(:rating, [1,2,3,4,5], :prompt => 'Rate') %>
</div>
<br>
<div class="field">
  <%= f.label :comment %>
  <br>
  <br>
  <%= f.text_area :comment, size: "30x5"  %>
</div>
<br>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/reviews/show.html.erb
<h1>Review for <%= @review.comicbook.title%>, issue <%= @review.comicbook.number%></h1>

<h2>Rating for this Comic book is: <%= @review.rating%> </h2>
<br>
<h2>COMMENTS<h2>
<h2><%= @review.comment%><h2>
<br>
<h2>Reviewed by the user: <%= @review.user.username%><h2>

<br>
<br>
<% if @review.user == current_user %>
<button type="button"><%= link_to 'Edit', edit_review_path(@review) %> </button>
<button type="button"><%= link_to 'Delete', @review, method: :delete, data: { confirm: 'Are you sure?' } %></button>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= form_for(@user, url:'/signup') do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email, required:true%>
  <br>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <br>
  <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome,  <%= @user.username %></h1>
<h2><%= link_to "Display My Comicbooks", comicbooks_path %></h2>
<h2><%= link_to "Add New Comicbook", new_comicbook_path %></h2>
<br>
<%= form_tag("/logout", method: "delete") do %>
<%= submit_tag("Logout") %>
<% end %>